# Generated by Django 3.1.5 on 2021-05-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetextractor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
