# Generated by Django 3.1.5 on 2021-05-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetextractor', '0003_auto_20210518_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_len',
        ),
    ]
