# Generated by Django 3.2.3 on 2021-05-19 17:19

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('tweetextractor', '0006_alter_tweet_tweet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_hashtags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
