# Generated by Django 3.2.3 on 2021-05-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetextractor', '0009_alter_tweet_tweet_cleaned_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tweet_hashtags',
            new_name='tags',
        ),
    ]
