# Generated by Django 3.2.3 on 2021-05-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetextractor', '0011_rename_tags_tweet_tweet_hashtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_user_id', models.CharField(blank=True, max_length=250, null=True)),
                ('twitter_name', models.TextField()),
                ('twitter_screen_name', models.TextField()),
                ('twitter_location', models.TextField()),
            ],
        ),
    ]
