# Generated by Django 3.2.3 on 2021-05-20 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweetextractor', '0012_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='tweetextractor.accounts'),
        ),
    ]
