# Generated by Django 3.2.3 on 2021-05-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetextractor', '0013_tweet_tweet_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_retweeted',
            field=models.BooleanField(default=False),
        ),
    ]
